In [1]:
import pandas as pd
import pandasql as ps

### Understanding our data

In [2]:
df = pd.read_excel (r'cars_crawling.xlsx', header=0)

#### Delete NaN values

In [3]:
#ניקוי נתונים חסרים ועמודות לא רלוונטיות
df=df[df.price!='None']
df=df[df.price!='לא צוין מחיר']
df=df[df.color!='בעלות נוכחית: פרטית']
del df['sub_type']
del df['Unnamed: 0']
df=df.dropna(axis=0)

#### Value change

In [4]:
#דירוג הצבעים ללבן, שחור וצבעוני
replace_map= {'לבן':1,
                'לבן פנינה':1,
                'לבן מטאלי':1,
                'לבן שנהב':1,
                'ברונזה':2,
                'תכלת':2,
                'אפור עכבר':2,
                'אפור מטאלי':2,
                'כחול כהה':2,
                'כחול כהה מטאלי':2,
                'ירוק מטאלי':2,
                'כסוף מטאלי':2,
                'כסוף':2,
                'אפור':2,
                'כחול בהיר':2,
                'כסף מטלי':2,
                'זהב מטאלי':2,
                'תכלת מטאלי':2,
                'ברונזה מטאלי':2,
                'כחול':2,
                'ירוק':2,
                'כחול מטאלי':2,
                'אדום':2,
                'ירוק בהיר':2,
                'חום מטאלי':2,
                'אדום מטאלי':2,
                'זהב':2,
                'סגול חציל':2,
                'כחול בהיר מטאלי':2,
                'טורקיז':2,
                'פלטינה':2,
                'בורדו':2,
                'ירוק בקבוק':2,
                'צהוב מטאלי':2,
                'בורדו מטאלי':2,
                'כתום':2,
                'חרדל':2,
                'חום':2,
                'צהוב':2,
                'סגול':2,
                'ירקרק':2,
                'טוניק':2,
                'ורוד':2,
                'שמפניה':2,
                'סגול מטאלי':2,
                'קרם':2,
                "בז’ מטאלי":2,
                "בז’":2,
                'שחור מטאלי':3,
                'שחור':3}
df.replace(replace_map, inplace=True)

#תיקון סוג המנוע לדיזל, בנזין, היברדי או חשמלי
replace_map= {  'דיזל':1,
                'טורבו זידל':1,
                'בנזין':2,
                'טורבו בנזין':2,
                'גפ"ם / בנזין':2,
                'היברידי חשמל / בנזין':4,
                'חשמלי':3
                }
df.replace(replace_map, inplace=True)

#הפיכת הערים לקטגוריות
replace_map= {  'אזור מושבים בצפון':4,
'אזור חיפה וחוף הכרמל':4,
'אזור עכו - נהריה':4,
'אזור קריות':4,
'אזור עמק יזרעאל':4,
'אזור כרמיאל והסביבה':4,
'אזור יישובי השומרון':4,
'אזור זכרון - בנימינה':4,
'אזור טבריה והסביבה':4,
'אזור גליל ועמקים':4,
'אזור אשדוד - אשקלון':2,
'אזור מושבים בשפלה':2,
'אזור נתניה והסביבה':3,
'אזור רעננה - כפר סבא':3,
'אזור חדרה וישובי עמק חפר':3,
'אזור מושבים בשרון':3,
'אזור הוד השרון והסביבה':3,
'אזור קיסריה והסביבה':3,
'אזור ירושלים והסביבה':2,
'אזור תל אביב':2,
'אזור ראשל"צ והסביבה':2,
'אזור פתח תקוה והסביבה':2,
'אזור רמת גן - גבעתיים':2,
'אזור חולון - בת ים':2,
'אזור גדרה יבנה והסביבה':2,
'אזור בקעת אונו':2,
'אזור רמת השרון - הרצליה':2,
'אזור רמלה - לוד':2,
'אזור מודיעין והסביבה':2,
'אזור בית שמש והסביבה':2,
'אזור נס ציונה - רחובות':2,
'אזור מושבים באזור ירושלים':2,
'אזור מושבים במרכז':2,
'אזור באר שבע והסביבה':1,
'אזור מושבים בדרום':1,
'אזור אילת והערבה':1
}

df.replace(replace_map, inplace=True)

#הפיכת הדגמים לאנגלית 
#הסרת הדגם מעמודת החברה+דגם
#עמודה חדשה עם שרשור מודל ושנה
df['ModelAndYear'] = df['producer']+df['year']
df['model'] = df['producer']
df['producer'] = df.producer.str.split().str.get(0)
replace_map= {  'טויוטה':'TOYOTA',
'מאזדה':'MAZDA',
'יונדאי':'HYUNDAI',
'סקודה':'SKODA',
'פולקסווגן':'VW',
'קיה':'KIA',
'מרצדס':'MERCEDES',
'שברולט':'CHEVROLET',
'הונדה':'HONDA',
'סיאט':'SIAT',
'סוזוקי':'SUZUKI',
'ב.מ.וו':'BMW',
'רנו':'RENU',
'פיג’ו':'PEUGEOT',
'פורד':'FORD',
'אאודי':'AUDI',
'סובארו':'SUBARO',
'סיטרואן':'SITR',
'אופל':'OPAL',
'מיצובישי':'MITSUBISHI',
'ניסאן':'NISSAN',
'פיאט':'FIAT',
'וולוו':'VOLVO',
'אלפא':'ALFA',
'לקסוס':'LEXUS',
'דייהטסו':'DAIHATSU',
'מיני':'MINI',
'קרייזלר':'CHRYSLER',
'דאצ’יה':'DACIA',
'ביואיק':'BUICH',
'אינפיניטי':'INFINITI',
'קאדילק':'CADILLAC',
'פורשה':'PORCHE',
'יגואר':'JAGUAR',
'טסלה':'TESLA',
'סאנגיונג':'SANGYOUNG',
'אברת’':'ABARTH',
'דייהו':'DAEWOO',
'פונטיאק':'PONTIAC',
'סמארט':'SMART',
'מזראטי':'MAZARATI',
'דודג’':'DODGE',
'לנצ’יה':'LANCIA',
'רובר':'RUBER',
'סאאב':'SAAB',
'לינקולן':'LINCOLN',
'גרייט':'GRAET',
'אסטון':'ASTON'
}

df.replace(replace_map, inplace=True)

In [5]:
#(1)תיקון הגיר לידני(0) או גיר רגיל
df['gir'] = df['gir'].apply(lambda x: 0 if x == 'ידנית' else 1)
#תיקון הבעלות לפרטית(0) או לא פרטית(1)
df['baalot'] = df['baalot'].apply(lambda x: 0 if x == 'פרטית' or x == 'ייבוא אישי' or x == 'ייבוא מקביל' else 1)

In [6]:
df.to_excel("cars_cleaningT.xlsx")

In [7]:
df = pd.read_excel (r'cars_cleaningT.xlsx', header=0)
#הפיכת המחיר למספר, וניקוי כל המחירים מעל ממוצע + 3 סטויות תקן
df["price"]=df['price'].str.replace(",", "").astype(int)
df=df[df.price<df["price"].mean()+3*df["price"].std()]

In [8]:
#בניית טבלה המכילה לכל מודל ושנה את ממוצע המחירים וכמות סטיות תקן מהממוצע הכללי
carsSTD = ps.sqldf("select producer,model,year,ModelAndYear,avg(price) as price from df group by producer,model,year,ModelAndYear")
#בניית טבלה על ידי שאילתא
carsSTD['numSTD']=round(((carsSTD['price']-df["price"].mean())/df["price"].std())*4)/4#נוסחה לקבלת כמה סטויות תקן מהמממוצע
carsSTD.pop('price')
carsSTD.to_excel("carsSTD.xlsx")

In [9]:
#איחוד טבלת המקור שלנו עם הטבלה שבנינו למעלה כדי להוסיף פיצר של כמות סטויות תוקן
df= ps.sqldf("select df.*,carsSTD.numSTD from df left join carsSTD on df.ModelAndYear=carsSTD.ModelAndYear")

df.to_excel("cars_cleaning.xlsx")